# Generated by Django 6.0.7 on 2026-08-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(choices=[('mele', 'male'), ('female', 'female'), ('other_species', 'other spices')], default='none', max_length=20)),
                ('title', models.CharField(choices=[('mr', 'mr'), ('mrs', 'mrs')], default='none', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('request', models.CharField(max_length=700)),
            ],
        ),
    ]
