# Generated by Django 6.0.7 on 2026-08-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servicerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='pics',
            field=models.ImageField(blank=True, upload_to='services'),
        ),
        migrations.AddField(
            model_name='submission',
            name='github_lin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
