# Generated by Django 6.0.7 on 2026-08-07 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='agender',
        ),
        migrations.RemoveField(
            model_name='board',
            name='chair',
        ),
        migrations.RemoveField(
            model_name='board',
            name='participants',
        ),
        migrations.AddField(
            model_name='bixenv',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Agender',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
